controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.1
      max_vel_x: 0.5
      min_vel_theta: 0.1
      max_vel_theta: 1.0
      acc_lim_x: 0.25
      acc_lim_theta: 1.0
      decel_lim_x: -0.5
      decel_lim_theta: -1.0
      transform_tolerance: 0.1

      critics: ["RotateToGoal", "Oscillation", "ObstacleFootprint", "GoalAlign"]

      RotateToGoal:
        scale: 1.0

      Oscillation:
        scale: 10.0

      ObstacleFootprint:
        scale: 1.0

      GoalAlign:
        scale: 1.0